export const EXTENSION_EVENTS = Object.freeze({
  flowRecordedStep: "lumi_live_flow_recorded_step",
  flowRecordingChanged: "lumi_live_flow_recording_changed",
  lifecycle: "lumi_live_lifecycle",
  request: "lumi_live_request",
  targetChanged: "lumi_live_target_changed",
  translationState: "lumi_live_translation_state",
  videoAnalysisProgress: "lumi_live_video_analysis_progress",
});

export const STORAGE_KEYS = Object.freeze({
  apiKey: "lumiGeminiApiKey",
  groqApiKey: "lumiGroqApiKey",
  avatarMode: "lumiAvatarMode",
  capturedTabAssets: "lumiCapturedTabAssets",
  chatHistory: "lumiLocalChatHistory",
  elementHighlights: "lumiShowElementHighlights",
  fastMode: "lumiFastMode",
  fastWorkspaceGroupId: "lumiFastWorkspaceGroupId",
  fallingPetals: "lumiFallingPetals",
  recordedFlowDraft: "lumiRecordedFlowDraft",
  recordedFlows: "lumiRecordedFlows",
  legacyMcpUrl: "lumiMcpServerUrl",
  mcpDisabledTools: "lumiDisabledMcpTools",
  mcpConnectorCredentials: "lumiMcpConnectorCredentials",
  mcpServers: "lumiMcpServers",
  mcpToolPolicies: "lumiMcpToolPolicies",
  microphoneEnabled: "lumiMicrophoneEnabled",
  microphoneGrantedAt: "lumiMicrophoneGrantedAt",
  targetTabId: "lumiLiveTargetTabId",
  thinkingLevel: "lumiGeminiThinkingLevel",
  voice: "lumiGeminiVoice",
});
