export const EXTENSION_EVENTS = Object.freeze({
  lifecycle: "lumi_live_lifecycle",
  request: "lumi_live_request",
  attention: "lumi_live_attention",
  scheduledRun: "lumi_live_scheduled_run",
  targetChanged: "lumi_live_target_changed",
  translationState: "lumi_live_translation_state",
});

export const STORAGE_KEYS = Object.freeze({
  apiKey: "lumiGeminiApiKey",
  avatarMode: "lumiAvatarMode",
  capturedTabAssets: "lumiCapturedTabAssets",
  elementHighlights: "lumiShowElementHighlights",
  fallingPetals: "lumiFallingPetals",
  historyActiveConversation: "lumiHistoryActiveConversation",
  legacyMcpUrl: "lumiMcpServerUrl",
  mcpDisabledTools: "lumiDisabledMcpTools",
  mcpConnectorCredentials: "lumiMcpConnectorCredentials",
  mcpServers: "lumiMcpServers",
  mcpToolPolicies: "lumiMcpToolPolicies",
  microphoneEnabled: "lumiMicrophoneEnabled",
  microphoneGrantedAt: "lumiMicrophoneGrantedAt",
  qcAllowedDomains: "lumiQcAllowedDomains",
  qcActiveRun: "lumiQcActiveRun",
  qcDiscoveryEnabled: "lumiQcDiscoveryEnabled",
  qcRunApprovalToken: "lumiQcRunApprovalToken",
  qcServiceToken: "lumiQcServiceToken",
  qcServiceUrl: "lumiQcServiceUrl",
  targetTabId: "lumiLiveTargetTabId",
  thinkingLevel: "lumiGeminiThinkingLevel",
  voice: "lumiGeminiVoice",
});
